[core]
# Disable screen blanking and timeout
idle-time=0
require-input=false

[shell]
# Disable locking
locking=false
# Change background color to black
background-color=0x00000000
# Disable panels for kiosk use
panel-position=none
