require conf/distro/belaybox.conf

DISTRO = "belaybox-docker"
DISTRO_NAME = "BelayBox with Docker support (Pionix Pro Distro)"

# Add virtualization support
DISTRO_FEATURES:append = " virtualization"

# Graphics features
DISTRO_FEATURES:append = " opengl multiarch wayland vulkan"
DISTRO_FEATURES:remove = " x11 mesa-demos"


# Allow bitbake to use the host's docker for building container images
HOSTTOOLS += "docker"
