require conf/distro/poky.conf

DISTRO = "belaybox"
DISTRO_NAME = "BelayBox (Pionix Pro Distro)"
DISTRO_VERSION = "1.0"

# Graphics features
DISTRO_FEATURES:append = " opengl multiarch wayland vulkan"
DISTRO_FEATURES:remove = " x11 mesa-demos"

# System features
DISTRO_FEATURES:append = " systemd usrmerge pam rauc security tpm debuginfod"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

# Init system configuration
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
