[Unit]
After=sys-subsystem-net-devices-enu1u2.device
Wants=sys-subsystem-net-devices-enu1u2.device
After=sys-subsystem-net-devices-enu1u3.device
Wants=sys-subsystem-net-devices-enu1u3.device

After=systemd-networkd.service
Wants=systemd-networkd.service

[Service]
ExecStartPre=/lib/systemd/systemd-networkd-wait-online -i enu1u2 -i enu1u3 --operational-state=degraded --timeout=60
