# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Needed due to image.bbclass and logging.bbclass
BBFILES += "${TOPDIR}/source/poky/meta/classes-recipe/*.bbclass"
BBFILES += "${TOPDIR}/source/poky/meta/classes-global/*.bbclass"

# Our own classes
BBFILES += "${LAYERDIR}/classes/*.bbclass"

BBFILE_COLLECTIONS += "meta-belaybox"
BBFILE_PATTERN_meta-belaybox = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-belaybox = "99"

LAYERDEPENDS_meta-belaybox = "meta-everest"
LAYERSERIES_COMPAT_meta-belaybox = "wrynose"

SCRIPTS_PATH = "${LAYERDIR}/scripts"

GIT_REPOSITORY_URL ?= "git://git@github.com/PionixPro"
PREFIX_GIT_REPOSITORY ?= ""
