# config file should use the socket rather than a TCP connection
listener 0 /tmp/mosquitto.socket
# needed for the flutter GUI
listener 1883 127.0.0.1
set_tcp_nodelay true
allow_anonymous true
max_keepalive 0

# Connectivity for next display-app
listener 9001 172.17.0.1
protocol websockets